version: "3.4"
services:
  mywebapi:
    build:
      context: Server/MyWebAPI
      dockerfile: Dockerfile
    image: mywebapi:latest
    container_name: mywebapi
    hostname: mywebapi
    ports:
      - 80:80
    environment: 
      ConnectionStrings__AdventureWorksDatatabase: Server=adventure-works.db;Database=AdventureWorks;User Id=sa;Password=Password.123
    depends_on:
      - adventure-works.db
 
  adventure-works.db:
    container_name: adventure-works.db
    image: adventure_works:latest
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"